# Generated by Django 6.0 on 2026-02-04 12:12

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField()),
                ("duration", models.PositiveIntegerField(default=30)),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("Lviv", "Lviv, Shevchenka 80"),
                            ("Kyiv", "Kyiv, Khmelnytskogo 15"),
                            ("Odesa", "Varnenska 18"),
                        ],
                        max_length=20,
                    ),
                ),
                ("brief_complaints", models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="MedicalCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diagnosis", models.TextField(max_length=300)),
                ("treatment", models.TextField(max_length=300)),
                ("notes", models.TextField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "species",
                    models.CharField(
                        choices=[
                            ("dog", "Dog"),
                            ("cat", "Cat"),
                            ("bird", "Bird"),
                            ("domestic", "Domestic animal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("birth_date", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=20
                    ),
                ),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="image"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
