# Generated by Django 6.0 on 2025-12-22 10:48

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="location",
            field=models.CharField(
                choices=[
                    ("Lviv", "Lviv, Shevchenka 80"),
                    ("Kyiv", "Kyiv, Khmelnytskogo 15"),
                    ("Odesa", "Varnenska 18"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
