# Generated by Django 6.0 on 2026-01-01 17:57

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_appointment_location_alter_pet_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=20, region=None, unique=True
            ),
        ),
    ]
